// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: internal/transport/proto/actorbase.proto

package actorbasepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_ACTIVE   NodeStatus = 0
	NodeStatus_NODE_STATUS_DRAINING NodeStatus = 1
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_ACTIVE",
		1: "NODE_STATUS_DRAINING",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_ACTIVE":   0,
		"NODE_STATUS_DRAINING": 1,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_transport_proto_actorbase_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_internal_transport_proto_actorbase_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{0}
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // Codec.Marshal(req)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *SendRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // Codec.Marshal(resp)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WatchRoutingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRoutingRequest) Reset() {
	*x = WatchRoutingRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRoutingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRoutingRequest) ProtoMessage() {}

func (x *WatchRoutingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRoutingRequest.ProtoReflect.Descriptor instead.
func (*WatchRoutingRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{2}
}

func (x *WatchRoutingRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type SplitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	SplitKey      string                 `protobuf:"bytes,2,opt,name=split_key,json=splitKey,proto3" json:"split_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitRequest) Reset() {
	*x = SplitRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitRequest) ProtoMessage() {}

func (x *SplitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitRequest.ProtoReflect.Descriptor instead.
func (*SplitRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{3}
}

func (x *SplitRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *SplitRequest) GetSplitKey() string {
	if x != nil {
		return x.SplitKey
	}
	return ""
}

type SplitResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewPartitionId string                 `protobuf:"bytes,1,opt,name=new_partition_id,json=newPartitionId,proto3" json:"new_partition_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SplitResponse) Reset() {
	*x = SplitResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitResponse) ProtoMessage() {}

func (x *SplitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitResponse.ProtoReflect.Descriptor instead.
func (*SplitResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{4}
}

func (x *SplitResponse) GetNewPartitionId() string {
	if x != nil {
		return x.NewPartitionId
	}
	return ""
}

type MigrateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateRequest) Reset() {
	*x = MigrateRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateRequest) ProtoMessage() {}

func (x *MigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateRequest.ProtoReflect.Descriptor instead.
func (*MigrateRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{5}
}

func (x *MigrateRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *MigrateRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

type MigrateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateResponse) Reset() {
	*x = MigrateResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateResponse) ProtoMessage() {}

func (x *MigrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateResponse.ProtoReflect.Descriptor instead.
func (*MigrateResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{6}
}

type ExecuteSplitRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PartitionId    string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	SplitKey       string                 `protobuf:"bytes,2,opt,name=split_key,json=splitKey,proto3" json:"split_key,omitempty"`
	NewPartitionId string                 `protobuf:"bytes,3,opt,name=new_partition_id,json=newPartitionId,proto3" json:"new_partition_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteSplitRequest) Reset() {
	*x = ExecuteSplitRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSplitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSplitRequest) ProtoMessage() {}

func (x *ExecuteSplitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSplitRequest.ProtoReflect.Descriptor instead.
func (*ExecuteSplitRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteSplitRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *ExecuteSplitRequest) GetSplitKey() string {
	if x != nil {
		return x.SplitKey
	}
	return ""
}

func (x *ExecuteSplitRequest) GetNewPartitionId() string {
	if x != nil {
		return x.NewPartitionId
	}
	return ""
}

type ExecuteSplitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSplitResponse) Reset() {
	*x = ExecuteSplitResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSplitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSplitResponse) ProtoMessage() {}

func (x *ExecuteSplitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSplitResponse.ProtoReflect.Descriptor instead.
func (*ExecuteSplitResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{8}
}

type ExecuteMigrateOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	TargetAddress string                 `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteMigrateOutRequest) Reset() {
	*x = ExecuteMigrateOutRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteMigrateOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMigrateOutRequest) ProtoMessage() {}

func (x *ExecuteMigrateOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMigrateOutRequest.ProtoReflect.Descriptor instead.
func (*ExecuteMigrateOutRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteMigrateOutRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *ExecuteMigrateOutRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *ExecuteMigrateOutRequest) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

type ExecuteMigrateOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteMigrateOutResponse) Reset() {
	*x = ExecuteMigrateOutResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteMigrateOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMigrateOutResponse) ProtoMessage() {}

func (x *ExecuteMigrateOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMigrateOutResponse.ProtoReflect.Descriptor instead.
func (*ExecuteMigrateOutResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{10}
}

type PreparePartitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	KeyRangeStart string                 `protobuf:"bytes,2,opt,name=key_range_start,json=keyRangeStart,proto3" json:"key_range_start,omitempty"` // target PS가 올바른 파티션인지 검증용
	KeyRangeEnd   string                 `protobuf:"bytes,3,opt,name=key_range_end,json=keyRangeEnd,proto3" json:"key_range_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreparePartitionRequest) Reset() {
	*x = PreparePartitionRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparePartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparePartitionRequest) ProtoMessage() {}

func (x *PreparePartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparePartitionRequest.ProtoReflect.Descriptor instead.
func (*PreparePartitionRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{11}
}

func (x *PreparePartitionRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *PreparePartitionRequest) GetKeyRangeStart() string {
	if x != nil {
		return x.KeyRangeStart
	}
	return ""
}

func (x *PreparePartitionRequest) GetKeyRangeEnd() string {
	if x != nil {
		return x.KeyRangeEnd
	}
	return ""
}

type PreparePartitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreparePartitionResponse) Reset() {
	*x = PreparePartitionResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparePartitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparePartitionResponse) ProtoMessage() {}

func (x *PreparePartitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparePartitionResponse.ProtoReflect.Descriptor instead.
func (*PreparePartitionResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{12}
}

type RoutingTableProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Entries       []*RouteEntryProto     `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingTableProto) Reset() {
	*x = RoutingTableProto{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingTableProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingTableProto) ProtoMessage() {}

func (x *RoutingTableProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingTableProto.ProtoReflect.Descriptor instead.
func (*RoutingTableProto) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{13}
}

func (x *RoutingTableProto) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RoutingTableProto) GetEntries() []*RouteEntryProto {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RouteEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	KeyRangeStart string                 `protobuf:"bytes,2,opt,name=key_range_start,json=keyRangeStart,proto3" json:"key_range_start,omitempty"`
	KeyRangeEnd   string                 `protobuf:"bytes,3,opt,name=key_range_end,json=keyRangeEnd,proto3" json:"key_range_end,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeAddress   string                 `protobuf:"bytes,5,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	NodeStatus    NodeStatus             `protobuf:"varint,6,opt,name=node_status,json=nodeStatus,proto3,enum=actorbase.v1.NodeStatus" json:"node_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteEntryProto) Reset() {
	*x = RouteEntryProto{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEntryProto) ProtoMessage() {}

func (x *RouteEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEntryProto.ProtoReflect.Descriptor instead.
func (*RouteEntryProto) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{14}
}

func (x *RouteEntryProto) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *RouteEntryProto) GetKeyRangeStart() string {
	if x != nil {
		return x.KeyRangeStart
	}
	return ""
}

func (x *RouteEntryProto) GetKeyRangeEnd() string {
	if x != nil {
		return x.KeyRangeEnd
	}
	return ""
}

func (x *RouteEntryProto) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RouteEntryProto) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *RouteEntryProto) GetNodeStatus() NodeStatus {
	if x != nil {
		return x.NodeStatus
	}
	return NodeStatus_NODE_STATUS_ACTIVE
}

var File_internal_transport_proto_actorbase_proto protoreflect.FileDescriptor

const file_internal_transport_proto_actorbase_proto_rawDesc = "" +
	"\n" +
	"(internal/transport/proto/actorbase.proto\x12\factorbase.v1\"J\n" +
	"\vSendRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"(\n" +
	"\fSendResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"2\n" +
	"\x13WatchRoutingRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"N\n" +
	"\fSplitRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12\x1b\n" +
	"\tsplit_key\x18\x02 \x01(\tR\bsplitKey\"9\n" +
	"\rSplitResponse\x12(\n" +
	"\x10new_partition_id\x18\x01 \x01(\tR\x0enewPartitionId\"Y\n" +
	"\x0eMigrateRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\tR\ftargetNodeId\"\x11\n" +
	"\x0fMigrateResponse\"\x7f\n" +
	"\x13ExecuteSplitRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12\x1b\n" +
	"\tsplit_key\x18\x02 \x01(\tR\bsplitKey\x12(\n" +
	"\x10new_partition_id\x18\x03 \x01(\tR\x0enewPartitionId\"\x16\n" +
	"\x14ExecuteSplitResponse\"\x8a\x01\n" +
	"\x18ExecuteMigrateOutRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\tR\ftargetNodeId\x12%\n" +
	"\x0etarget_address\x18\x03 \x01(\tR\rtargetAddress\"\x1b\n" +
	"\x19ExecuteMigrateOutResponse\"\x88\x01\n" +
	"\x17PreparePartitionRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12&\n" +
	"\x0fkey_range_start\x18\x02 \x01(\tR\rkeyRangeStart\x12\"\n" +
	"\rkey_range_end\x18\x03 \x01(\tR\vkeyRangeEnd\"\x1a\n" +
	"\x18PreparePartitionResponse\"f\n" +
	"\x11RoutingTableProto\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x127\n" +
	"\aentries\x18\x02 \x03(\v2\x1d.actorbase.v1.RouteEntryProtoR\aentries\"\xf7\x01\n" +
	"\x0fRouteEntryProto\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12&\n" +
	"\x0fkey_range_start\x18\x02 \x01(\tR\rkeyRangeStart\x12\"\n" +
	"\rkey_range_end\x18\x03 \x01(\tR\vkeyRangeEnd\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12!\n" +
	"\fnode_address\x18\x05 \x01(\tR\vnodeAddress\x129\n" +
	"\vnode_status\x18\x06 \x01(\x0e2\x18.actorbase.v1.NodeStatusR\n" +
	"nodeStatus*>\n" +
	"\n" +
	"NodeStatus\x12\x16\n" +
	"\x12NODE_STATUS_ACTIVE\x10\x00\x12\x18\n" +
	"\x14NODE_STATUS_DRAINING\x10\x012Q\n" +
	"\x10PartitionService\x12=\n" +
	"\x04Send\x12\x19.actorbase.v1.SendRequest\x1a\x1a.actorbase.v1.SendResponse2\x87\x02\n" +
	"\x17PartitionManagerService\x12T\n" +
	"\fWatchRouting\x12!.actorbase.v1.WatchRoutingRequest\x1a\x1f.actorbase.v1.RoutingTableProto0\x01\x12G\n" +
	"\fRequestSplit\x12\x1a.actorbase.v1.SplitRequest\x1a\x1b.actorbase.v1.SplitResponse\x12M\n" +
	"\x0eRequestMigrate\x12\x1c.actorbase.v1.MigrateRequest\x1a\x1d.actorbase.v1.MigrateResponse2\xb9\x02\n" +
	"\x17PartitionControlService\x12U\n" +
	"\fExecuteSplit\x12!.actorbase.v1.ExecuteSplitRequest\x1a\".actorbase.v1.ExecuteSplitResponse\x12d\n" +
	"\x11ExecuteMigrateOut\x12&.actorbase.v1.ExecuteMigrateOutRequest\x1a'.actorbase.v1.ExecuteMigrateOutResponse\x12a\n" +
	"\x10PreparePartition\x12%.actorbase.v1.PreparePartitionRequest\x1a&.actorbase.v1.PreparePartitionResponseBBZ@github.com/oomymy/actorbase/internal/transport/proto;actorbasepbb\x06proto3"

var (
	file_internal_transport_proto_actorbase_proto_rawDescOnce sync.Once
	file_internal_transport_proto_actorbase_proto_rawDescData []byte
)

func file_internal_transport_proto_actorbase_proto_rawDescGZIP() []byte {
	file_internal_transport_proto_actorbase_proto_rawDescOnce.Do(func() {
		file_internal_transport_proto_actorbase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_proto_actorbase_proto_rawDesc), len(file_internal_transport_proto_actorbase_proto_rawDesc)))
	})
	return file_internal_transport_proto_actorbase_proto_rawDescData
}

var file_internal_transport_proto_actorbase_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_transport_proto_actorbase_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_transport_proto_actorbase_proto_goTypes = []any{
	(NodeStatus)(0),                   // 0: actorbase.v1.NodeStatus
	(*SendRequest)(nil),               // 1: actorbase.v1.SendRequest
	(*SendResponse)(nil),              // 2: actorbase.v1.SendResponse
	(*WatchRoutingRequest)(nil),       // 3: actorbase.v1.WatchRoutingRequest
	(*SplitRequest)(nil),              // 4: actorbase.v1.SplitRequest
	(*SplitResponse)(nil),             // 5: actorbase.v1.SplitResponse
	(*MigrateRequest)(nil),            // 6: actorbase.v1.MigrateRequest
	(*MigrateResponse)(nil),           // 7: actorbase.v1.MigrateResponse
	(*ExecuteSplitRequest)(nil),       // 8: actorbase.v1.ExecuteSplitRequest
	(*ExecuteSplitResponse)(nil),      // 9: actorbase.v1.ExecuteSplitResponse
	(*ExecuteMigrateOutRequest)(nil),  // 10: actorbase.v1.ExecuteMigrateOutRequest
	(*ExecuteMigrateOutResponse)(nil), // 11: actorbase.v1.ExecuteMigrateOutResponse
	(*PreparePartitionRequest)(nil),   // 12: actorbase.v1.PreparePartitionRequest
	(*PreparePartitionResponse)(nil),  // 13: actorbase.v1.PreparePartitionResponse
	(*RoutingTableProto)(nil),         // 14: actorbase.v1.RoutingTableProto
	(*RouteEntryProto)(nil),           // 15: actorbase.v1.RouteEntryProto
}
var file_internal_transport_proto_actorbase_proto_depIdxs = []int32{
	15, // 0: actorbase.v1.RoutingTableProto.entries:type_name -> actorbase.v1.RouteEntryProto
	0,  // 1: actorbase.v1.RouteEntryProto.node_status:type_name -> actorbase.v1.NodeStatus
	1,  // 2: actorbase.v1.PartitionService.Send:input_type -> actorbase.v1.SendRequest
	3,  // 3: actorbase.v1.PartitionManagerService.WatchRouting:input_type -> actorbase.v1.WatchRoutingRequest
	4,  // 4: actorbase.v1.PartitionManagerService.RequestSplit:input_type -> actorbase.v1.SplitRequest
	6,  // 5: actorbase.v1.PartitionManagerService.RequestMigrate:input_type -> actorbase.v1.MigrateRequest
	8,  // 6: actorbase.v1.PartitionControlService.ExecuteSplit:input_type -> actorbase.v1.ExecuteSplitRequest
	10, // 7: actorbase.v1.PartitionControlService.ExecuteMigrateOut:input_type -> actorbase.v1.ExecuteMigrateOutRequest
	12, // 8: actorbase.v1.PartitionControlService.PreparePartition:input_type -> actorbase.v1.PreparePartitionRequest
	2,  // 9: actorbase.v1.PartitionService.Send:output_type -> actorbase.v1.SendResponse
	14, // 10: actorbase.v1.PartitionManagerService.WatchRouting:output_type -> actorbase.v1.RoutingTableProto
	5,  // 11: actorbase.v1.PartitionManagerService.RequestSplit:output_type -> actorbase.v1.SplitResponse
	7,  // 12: actorbase.v1.PartitionManagerService.RequestMigrate:output_type -> actorbase.v1.MigrateResponse
	9,  // 13: actorbase.v1.PartitionControlService.ExecuteSplit:output_type -> actorbase.v1.ExecuteSplitResponse
	11, // 14: actorbase.v1.PartitionControlService.ExecuteMigrateOut:output_type -> actorbase.v1.ExecuteMigrateOutResponse
	13, // 15: actorbase.v1.PartitionControlService.PreparePartition:output_type -> actorbase.v1.PreparePartitionResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_transport_proto_actorbase_proto_init() }
func file_internal_transport_proto_actorbase_proto_init() {
	if File_internal_transport_proto_actorbase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_proto_actorbase_proto_rawDesc), len(file_internal_transport_proto_actorbase_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_internal_transport_proto_actorbase_proto_goTypes,
		DependencyIndexes: file_internal_transport_proto_actorbase_proto_depIdxs,
		EnumInfos:         file_internal_transport_proto_actorbase_proto_enumTypes,
		MessageInfos:      file_internal_transport_proto_actorbase_proto_msgTypes,
	}.Build()
	File_internal_transport_proto_actorbase_proto = out.File
	file_internal_transport_proto_actorbase_proto_goTypes = nil
	file_internal_transport_proto_actorbase_proto_depIdxs = nil
}
