// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.23.4
// source: internal/transport/proto/actorbase.proto

package actorbasepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PartitionService_Send_FullMethodName = "/actorbase.v1.PartitionService/Send"
	PartitionService_Scan_FullMethodName = "/actorbase.v1.PartitionService/Scan"
)

// PartitionServiceClient is the client API for PartitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartitionServiceClient interface {
	// Send는 partitionID의 Actor에게 요청을 전달하고 응답을 반환한다.
	// payload는 Codec으로 직렬화된 사용자 정의 Req 타입이다.
	// 에러는 gRPC status code로 전달한다.
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	// Scan은 파티션 내에서 범위 조회를 수행한다.
	// Send와 동일하게 Actor.Receive()를 호출하지만, expected key range를 함께 전달하여
	// stale 라우팅으로 인한 누락을 방지한다.
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
}

type partitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartitionServiceClient(cc grpc.ClientConnInterface) PartitionServiceClient {
	return &partitionServiceClient{cc}
}

func (c *partitionServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, PartitionService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionServiceClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, PartitionService_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartitionServiceServer is the server API for PartitionService service.
// All implementations must embed UnimplementedPartitionServiceServer
// for forward compatibility.
type PartitionServiceServer interface {
	// Send는 partitionID의 Actor에게 요청을 전달하고 응답을 반환한다.
	// payload는 Codec으로 직렬화된 사용자 정의 Req 타입이다.
	// 에러는 gRPC status code로 전달한다.
	Send(context.Context, *SendRequest) (*SendResponse, error)
	// Scan은 파티션 내에서 범위 조회를 수행한다.
	// Send와 동일하게 Actor.Receive()를 호출하지만, expected key range를 함께 전달하여
	// stale 라우팅으로 인한 누락을 방지한다.
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	mustEmbedUnimplementedPartitionServiceServer()
}

// UnimplementedPartitionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartitionServiceServer struct{}

func (UnimplementedPartitionServiceServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedPartitionServiceServer) Scan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedPartitionServiceServer) mustEmbedUnimplementedPartitionServiceServer() {}
func (UnimplementedPartitionServiceServer) testEmbeddedByValue()                          {}

// UnsafePartitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartitionServiceServer will
// result in compilation errors.
type UnsafePartitionServiceServer interface {
	mustEmbedUnimplementedPartitionServiceServer()
}

func RegisterPartitionServiceServer(s grpc.ServiceRegistrar, srv PartitionServiceServer) {
	// If the following call panics, it indicates UnimplementedPartitionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartitionService_ServiceDesc, srv)
}

func _PartitionService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartitionService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionServiceServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartitionService_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionServiceServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartitionService_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionServiceServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartitionService_ServiceDesc is the grpc.ServiceDesc for PartitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "actorbase.v1.PartitionService",
	HandlerType: (*PartitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _PartitionService_Send_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _PartitionService_Scan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/transport/proto/actorbase.proto",
}

const (
	PartitionManagerService_WatchRouting_FullMethodName    = "/actorbase.v1.PartitionManagerService/WatchRouting"
	PartitionManagerService_RequestSplit_FullMethodName    = "/actorbase.v1.PartitionManagerService/RequestSplit"
	PartitionManagerService_RequestMigrate_FullMethodName  = "/actorbase.v1.PartitionManagerService/RequestMigrate"
	PartitionManagerService_ListMembers_FullMethodName     = "/actorbase.v1.PartitionManagerService/ListMembers"
	PartitionManagerService_GetClusterStats_FullMethodName = "/actorbase.v1.PartitionManagerService/GetClusterStats"
	PartitionManagerService_ApplyPolicy_FullMethodName     = "/actorbase.v1.PartitionManagerService/ApplyPolicy"
	PartitionManagerService_GetPolicy_FullMethodName       = "/actorbase.v1.PartitionManagerService/GetPolicy"
	PartitionManagerService_ClearPolicy_FullMethodName     = "/actorbase.v1.PartitionManagerService/ClearPolicy"
)

// PartitionManagerServiceClient is the client API for PartitionManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartitionManagerServiceClient interface {
	// WatchRouting은 연결 즉시 현재 라우팅 테이블을 전송하고,
	// 이후 변경이 생길 때마다 스트리밍으로 push한다.
	WatchRouting(ctx context.Context, in *WatchRoutingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoutingTableProto], error)
	// RequestSplit은 파티션 split을 PM에 요청한다.
	// actor_type을 명시해야 하며, partitionID의 actor_type과 일치하지 않으면 에러.
	RequestSplit(ctx context.Context, in *SplitRequest, opts ...grpc.CallOption) (*SplitResponse, error)
	// RequestMigrate는 파티션 migration을 PM에 요청한다.
	// actor_type을 명시해야 하며, partitionID의 actor_type과 일치하지 않으면 에러.
	RequestMigrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error)
	// ListMembers는 현재 등록된 PS 노드 목록을 반환한다.
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	// GetClusterStats는 클러스터 전체(또는 특정 노드)의 통계를 반환한다.
	// node_id가 빈 문자열이면 모든 노드의 통계를 반환한다.
	GetClusterStats(ctx context.Context, in *GetClusterStatsRequest, opts ...grpc.CallOption) (*GetClusterStatsResponse, error)
	// ApplyPolicy는 YAML 정책을 PM에 적용하고 etcd에 영속화한다. AutoPolicy 활성화.
	ApplyPolicy(ctx context.Context, in *ApplyPolicyRequest, opts ...grpc.CallOption) (*ApplyPolicyResponse, error)
	// GetPolicy는 현재 적용 중인 정책 YAML을 반환한다.
	GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*GetPolicyResponse, error)
	// ClearPolicy는 정책을 제거하여 ManualPolicy로 전환한다.
	ClearPolicy(ctx context.Context, in *ClearPolicyRequest, opts ...grpc.CallOption) (*ClearPolicyResponse, error)
}

type partitionManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartitionManagerServiceClient(cc grpc.ClientConnInterface) PartitionManagerServiceClient {
	return &partitionManagerServiceClient{cc}
}

func (c *partitionManagerServiceClient) WatchRouting(ctx context.Context, in *WatchRoutingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoutingTableProto], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PartitionManagerService_ServiceDesc.Streams[0], PartitionManagerService_WatchRouting_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRoutingRequest, RoutingTableProto]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PartitionManagerService_WatchRoutingClient = grpc.ServerStreamingClient[RoutingTableProto]

func (c *partitionManagerServiceClient) RequestSplit(ctx context.Context, in *SplitRequest, opts ...grpc.CallOption) (*SplitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SplitResponse)
	err := c.cc.Invoke(ctx, PartitionManagerService_RequestSplit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionManagerServiceClient) RequestMigrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateResponse)
	err := c.cc.Invoke(ctx, PartitionManagerService_RequestMigrate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionManagerServiceClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, PartitionManagerService_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionManagerServiceClient) GetClusterStats(ctx context.Context, in *GetClusterStatsRequest, opts ...grpc.CallOption) (*GetClusterStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterStatsResponse)
	err := c.cc.Invoke(ctx, PartitionManagerService_GetClusterStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionManagerServiceClient) ApplyPolicy(ctx context.Context, in *ApplyPolicyRequest, opts ...grpc.CallOption) (*ApplyPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyPolicyResponse)
	err := c.cc.Invoke(ctx, PartitionManagerService_ApplyPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionManagerServiceClient) GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*GetPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPolicyResponse)
	err := c.cc.Invoke(ctx, PartitionManagerService_GetPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionManagerServiceClient) ClearPolicy(ctx context.Context, in *ClearPolicyRequest, opts ...grpc.CallOption) (*ClearPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearPolicyResponse)
	err := c.cc.Invoke(ctx, PartitionManagerService_ClearPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartitionManagerServiceServer is the server API for PartitionManagerService service.
// All implementations must embed UnimplementedPartitionManagerServiceServer
// for forward compatibility.
type PartitionManagerServiceServer interface {
	// WatchRouting은 연결 즉시 현재 라우팅 테이블을 전송하고,
	// 이후 변경이 생길 때마다 스트리밍으로 push한다.
	WatchRouting(*WatchRoutingRequest, grpc.ServerStreamingServer[RoutingTableProto]) error
	// RequestSplit은 파티션 split을 PM에 요청한다.
	// actor_type을 명시해야 하며, partitionID의 actor_type과 일치하지 않으면 에러.
	RequestSplit(context.Context, *SplitRequest) (*SplitResponse, error)
	// RequestMigrate는 파티션 migration을 PM에 요청한다.
	// actor_type을 명시해야 하며, partitionID의 actor_type과 일치하지 않으면 에러.
	RequestMigrate(context.Context, *MigrateRequest) (*MigrateResponse, error)
	// ListMembers는 현재 등록된 PS 노드 목록을 반환한다.
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error)
	// GetClusterStats는 클러스터 전체(또는 특정 노드)의 통계를 반환한다.
	// node_id가 빈 문자열이면 모든 노드의 통계를 반환한다.
	GetClusterStats(context.Context, *GetClusterStatsRequest) (*GetClusterStatsResponse, error)
	// ApplyPolicy는 YAML 정책을 PM에 적용하고 etcd에 영속화한다. AutoPolicy 활성화.
	ApplyPolicy(context.Context, *ApplyPolicyRequest) (*ApplyPolicyResponse, error)
	// GetPolicy는 현재 적용 중인 정책 YAML을 반환한다.
	GetPolicy(context.Context, *GetPolicyRequest) (*GetPolicyResponse, error)
	// ClearPolicy는 정책을 제거하여 ManualPolicy로 전환한다.
	ClearPolicy(context.Context, *ClearPolicyRequest) (*ClearPolicyResponse, error)
	mustEmbedUnimplementedPartitionManagerServiceServer()
}

// UnimplementedPartitionManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartitionManagerServiceServer struct{}

func (UnimplementedPartitionManagerServiceServer) WatchRouting(*WatchRoutingRequest, grpc.ServerStreamingServer[RoutingTableProto]) error {
	return status.Error(codes.Unimplemented, "method WatchRouting not implemented")
}
func (UnimplementedPartitionManagerServiceServer) RequestSplit(context.Context, *SplitRequest) (*SplitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestSplit not implemented")
}
func (UnimplementedPartitionManagerServiceServer) RequestMigrate(context.Context, *MigrateRequest) (*MigrateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestMigrate not implemented")
}
func (UnimplementedPartitionManagerServiceServer) ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedPartitionManagerServiceServer) GetClusterStats(context.Context, *GetClusterStatsRequest) (*GetClusterStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterStats not implemented")
}
func (UnimplementedPartitionManagerServiceServer) ApplyPolicy(context.Context, *ApplyPolicyRequest) (*ApplyPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyPolicy not implemented")
}
func (UnimplementedPartitionManagerServiceServer) GetPolicy(context.Context, *GetPolicyRequest) (*GetPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicy not implemented")
}
func (UnimplementedPartitionManagerServiceServer) ClearPolicy(context.Context, *ClearPolicyRequest) (*ClearPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearPolicy not implemented")
}
func (UnimplementedPartitionManagerServiceServer) mustEmbedUnimplementedPartitionManagerServiceServer() {
}
func (UnimplementedPartitionManagerServiceServer) testEmbeddedByValue() {}

// UnsafePartitionManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartitionManagerServiceServer will
// result in compilation errors.
type UnsafePartitionManagerServiceServer interface {
	mustEmbedUnimplementedPartitionManagerServiceServer()
}

func RegisterPartitionManagerServiceServer(s grpc.ServiceRegistrar, srv PartitionManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedPartitionManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartitionManagerService_ServiceDesc, srv)
}

func _PartitionManagerService_WatchRouting_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRoutingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PartitionManagerServiceServer).WatchRouting(m, &grpc.GenericServerStream[WatchRoutingRequest, RoutingTableProto]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PartitionManagerService_WatchRoutingServer = grpc.ServerStreamingServer[RoutingTableProto]

func _PartitionManagerService_RequestSplit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionManagerServiceServer).RequestSplit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartitionManagerService_RequestSplit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionManagerServiceServer).RequestSplit(ctx, req.(*SplitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartitionManagerService_RequestMigrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionManagerServiceServer).RequestMigrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartitionManagerService_RequestMigrate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionManagerServiceServer).RequestMigrate(ctx, req.(*MigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartitionManagerService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionManagerServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartitionManagerService_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionManagerServiceServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartitionManagerService_GetClusterStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionManagerServiceServer).GetClusterStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartitionManagerService_GetClusterStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionManagerServiceServer).GetClusterStats(ctx, req.(*GetClusterStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartitionManagerService_ApplyPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionManagerServiceServer).ApplyPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartitionManagerService_ApplyPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionManagerServiceServer).ApplyPolicy(ctx, req.(*ApplyPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartitionManagerService_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionManagerServiceServer).GetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartitionManagerService_GetPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionManagerServiceServer).GetPolicy(ctx, req.(*GetPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartitionManagerService_ClearPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionManagerServiceServer).ClearPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartitionManagerService_ClearPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionManagerServiceServer).ClearPolicy(ctx, req.(*ClearPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartitionManagerService_ServiceDesc is the grpc.ServiceDesc for PartitionManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartitionManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "actorbase.v1.PartitionManagerService",
	HandlerType: (*PartitionManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestSplit",
			Handler:    _PartitionManagerService_RequestSplit_Handler,
		},
		{
			MethodName: "RequestMigrate",
			Handler:    _PartitionManagerService_RequestMigrate_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _PartitionManagerService_ListMembers_Handler,
		},
		{
			MethodName: "GetClusterStats",
			Handler:    _PartitionManagerService_GetClusterStats_Handler,
		},
		{
			MethodName: "ApplyPolicy",
			Handler:    _PartitionManagerService_ApplyPolicy_Handler,
		},
		{
			MethodName: "GetPolicy",
			Handler:    _PartitionManagerService_GetPolicy_Handler,
		},
		{
			MethodName: "ClearPolicy",
			Handler:    _PartitionManagerService_ClearPolicy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchRouting",
			Handler:       _PartitionManagerService_WatchRouting_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/transport/proto/actorbase.proto",
}

const (
	PartitionControlService_GetStats_FullMethodName          = "/actorbase.v1.PartitionControlService/GetStats"
	PartitionControlService_ExecuteSplit_FullMethodName      = "/actorbase.v1.PartitionControlService/ExecuteSplit"
	PartitionControlService_ExecuteMigrateOut_FullMethodName = "/actorbase.v1.PartitionControlService/ExecuteMigrateOut"
	PartitionControlService_PreparePartition_FullMethodName  = "/actorbase.v1.PartitionControlService/PreparePartition"
)

// PartitionControlServiceClient is the client API for PartitionControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartitionControlServiceClient interface {
	// GetStats는 PM이 PS에게 노드 전체 통계를 요청한다.
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	// ExecuteSplit은 PM이 PS에게 파티션 split을 명령한다.
	ExecuteSplit(ctx context.Context, in *ExecuteSplitRequest, opts ...grpc.CallOption) (*ExecuteSplitResponse, error)
	// ExecuteMigrateOut은 PM이 PS에게 파티션을 대상 노드로 이동시키도록 명령한다.
	ExecuteMigrateOut(ctx context.Context, in *ExecuteMigrateOutRequest, opts ...grpc.CallOption) (*ExecuteMigrateOutResponse, error)
	// PreparePartition은 PM이 target PS에게 파티션을 CheckpointStore에서 로드하도록 명령한다.
	PreparePartition(ctx context.Context, in *PreparePartitionRequest, opts ...grpc.CallOption) (*PreparePartitionResponse, error)
}

type partitionControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartitionControlServiceClient(cc grpc.ClientConnInterface) PartitionControlServiceClient {
	return &partitionControlServiceClient{cc}
}

func (c *partitionControlServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, PartitionControlService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionControlServiceClient) ExecuteSplit(ctx context.Context, in *ExecuteSplitRequest, opts ...grpc.CallOption) (*ExecuteSplitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteSplitResponse)
	err := c.cc.Invoke(ctx, PartitionControlService_ExecuteSplit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionControlServiceClient) ExecuteMigrateOut(ctx context.Context, in *ExecuteMigrateOutRequest, opts ...grpc.CallOption) (*ExecuteMigrateOutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteMigrateOutResponse)
	err := c.cc.Invoke(ctx, PartitionControlService_ExecuteMigrateOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionControlServiceClient) PreparePartition(ctx context.Context, in *PreparePartitionRequest, opts ...grpc.CallOption) (*PreparePartitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreparePartitionResponse)
	err := c.cc.Invoke(ctx, PartitionControlService_PreparePartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartitionControlServiceServer is the server API for PartitionControlService service.
// All implementations must embed UnimplementedPartitionControlServiceServer
// for forward compatibility.
type PartitionControlServiceServer interface {
	// GetStats는 PM이 PS에게 노드 전체 통계를 요청한다.
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	// ExecuteSplit은 PM이 PS에게 파티션 split을 명령한다.
	ExecuteSplit(context.Context, *ExecuteSplitRequest) (*ExecuteSplitResponse, error)
	// ExecuteMigrateOut은 PM이 PS에게 파티션을 대상 노드로 이동시키도록 명령한다.
	ExecuteMigrateOut(context.Context, *ExecuteMigrateOutRequest) (*ExecuteMigrateOutResponse, error)
	// PreparePartition은 PM이 target PS에게 파티션을 CheckpointStore에서 로드하도록 명령한다.
	PreparePartition(context.Context, *PreparePartitionRequest) (*PreparePartitionResponse, error)
	mustEmbedUnimplementedPartitionControlServiceServer()
}

// UnimplementedPartitionControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartitionControlServiceServer struct{}

func (UnimplementedPartitionControlServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedPartitionControlServiceServer) ExecuteSplit(context.Context, *ExecuteSplitRequest) (*ExecuteSplitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteSplit not implemented")
}
func (UnimplementedPartitionControlServiceServer) ExecuteMigrateOut(context.Context, *ExecuteMigrateOutRequest) (*ExecuteMigrateOutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteMigrateOut not implemented")
}
func (UnimplementedPartitionControlServiceServer) PreparePartition(context.Context, *PreparePartitionRequest) (*PreparePartitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreparePartition not implemented")
}
func (UnimplementedPartitionControlServiceServer) mustEmbedUnimplementedPartitionControlServiceServer() {
}
func (UnimplementedPartitionControlServiceServer) testEmbeddedByValue() {}

// UnsafePartitionControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartitionControlServiceServer will
// result in compilation errors.
type UnsafePartitionControlServiceServer interface {
	mustEmbedUnimplementedPartitionControlServiceServer()
}

func RegisterPartitionControlServiceServer(s grpc.ServiceRegistrar, srv PartitionControlServiceServer) {
	// If the following call panics, it indicates UnimplementedPartitionControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartitionControlService_ServiceDesc, srv)
}

func _PartitionControlService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionControlServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartitionControlService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionControlServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartitionControlService_ExecuteSplit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSplitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionControlServiceServer).ExecuteSplit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartitionControlService_ExecuteSplit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionControlServiceServer).ExecuteSplit(ctx, req.(*ExecuteSplitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartitionControlService_ExecuteMigrateOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteMigrateOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionControlServiceServer).ExecuteMigrateOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartitionControlService_ExecuteMigrateOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionControlServiceServer).ExecuteMigrateOut(ctx, req.(*ExecuteMigrateOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartitionControlService_PreparePartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreparePartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionControlServiceServer).PreparePartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartitionControlService_PreparePartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionControlServiceServer).PreparePartition(ctx, req.(*PreparePartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartitionControlService_ServiceDesc is the grpc.ServiceDesc for PartitionControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartitionControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "actorbase.v1.PartitionControlService",
	HandlerType: (*PartitionControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _PartitionControlService_GetStats_Handler,
		},
		{
			MethodName: "ExecuteSplit",
			Handler:    _PartitionControlService_ExecuteSplit_Handler,
		},
		{
			MethodName: "ExecuteMigrateOut",
			Handler:    _PartitionControlService_ExecuteMigrateOut_Handler,
		},
		{
			MethodName: "PreparePartition",
			Handler:    _PartitionControlService_PreparePartition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/transport/proto/actorbase.proto",
}
