// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: internal/transport/proto/actorbase.proto

package actorbasepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_ACTIVE   NodeStatus = 0
	NodeStatus_NODE_STATUS_DRAINING NodeStatus = 1
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_ACTIVE",
		1: "NODE_STATUS_DRAINING",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_ACTIVE":   0,
		"NODE_STATUS_DRAINING": 1,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_transport_proto_actorbase_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_internal_transport_proto_actorbase_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{0}
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                      // Codec.Marshal(req)
	ActorType     string                 `protobuf:"bytes,3,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"` // actor type 식별자. PS가 올바른 ActorHost로 라우팅하는 데 사용.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *SendRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // Codec.Marshal(resp)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ScanRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PartitionId           string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Payload               []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // Codec.Marshal(req)
	ActorType             string                 `protobuf:"bytes,3,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ExpectedKeyRangeStart string                 `protobuf:"bytes,4,opt,name=expected_key_range_start,json=expectedKeyRangeStart,proto3" json:"expected_key_range_start,omitempty"` // SDK가 알고 있는 파티션 key range (stale routing 감지용)
	ExpectedKeyRangeEnd   string                 `protobuf:"bytes,5,opt,name=expected_key_range_end,json=expectedKeyRangeEnd,proto3" json:"expected_key_range_end,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{2}
}

func (x *ScanRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *ScanRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ScanRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *ScanRequest) GetExpectedKeyRangeStart() string {
	if x != nil {
		return x.ExpectedKeyRangeStart
	}
	return ""
}

func (x *ScanRequest) GetExpectedKeyRangeEnd() string {
	if x != nil {
		return x.ExpectedKeyRangeEnd
	}
	return ""
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // Codec.Marshal(resp) — Resp는 actor가 리스트 타입으로 정의
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{3}
}

func (x *ScanResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WatchRoutingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRoutingRequest) Reset() {
	*x = WatchRoutingRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRoutingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRoutingRequest) ProtoMessage() {}

func (x *WatchRoutingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRoutingRequest.ProtoReflect.Descriptor instead.
func (*WatchRoutingRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{4}
}

func (x *WatchRoutingRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type SplitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	SplitKey      string                 `protobuf:"bytes,2,opt,name=split_key,json=splitKey,proto3" json:"split_key,omitempty"`
	ActorType     string                 `protobuf:"bytes,3,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"` // 사용자가 명시. PM이 파티션의 실제 actor_type과 검증한다.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitRequest) Reset() {
	*x = SplitRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitRequest) ProtoMessage() {}

func (x *SplitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitRequest.ProtoReflect.Descriptor instead.
func (*SplitRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{5}
}

func (x *SplitRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *SplitRequest) GetSplitKey() string {
	if x != nil {
		return x.SplitKey
	}
	return ""
}

func (x *SplitRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

type SplitResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewPartitionId string                 `protobuf:"bytes,1,opt,name=new_partition_id,json=newPartitionId,proto3" json:"new_partition_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SplitResponse) Reset() {
	*x = SplitResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitResponse) ProtoMessage() {}

func (x *SplitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitResponse.ProtoReflect.Descriptor instead.
func (*SplitResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{6}
}

func (x *SplitResponse) GetNewPartitionId() string {
	if x != nil {
		return x.NewPartitionId
	}
	return ""
}

type MigrateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	ActorType     string                 `protobuf:"bytes,3,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"` // 사용자가 명시. PM이 파티션의 실제 actor_type과 검증한다.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateRequest) Reset() {
	*x = MigrateRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateRequest) ProtoMessage() {}

func (x *MigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateRequest.ProtoReflect.Descriptor instead.
func (*MigrateRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{7}
}

func (x *MigrateRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *MigrateRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *MigrateRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

type MigrateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateResponse) Reset() {
	*x = MigrateResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateResponse) ProtoMessage() {}

func (x *MigrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateResponse.ProtoReflect.Descriptor instead.
func (*MigrateResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{8}
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{9}
}

type MemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Status        NodeStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=actorbase.v1.NodeStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfo) Reset() {
	*x = MemberInfo{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfo) ProtoMessage() {}

func (x *MemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfo.ProtoReflect.Descriptor instead.
func (*MemberInfo) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{10}
}

func (x *MemberInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MemberInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MemberInfo) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_ACTIVE
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*MemberInfo          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{11}
}

func (x *ListMembersResponse) GetMembers() []*MemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

type ExecuteSplitRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PartitionId    string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	SplitKey       string                 `protobuf:"bytes,2,opt,name=split_key,json=splitKey,proto3" json:"split_key,omitempty"` // 비어 있으면 PS가 SplitHinter 또는 key range midpoint로 결정
	NewPartitionId string                 `protobuf:"bytes,3,opt,name=new_partition_id,json=newPartitionId,proto3" json:"new_partition_id,omitempty"`
	ActorType      string                 `protobuf:"bytes,4,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`               // PS가 올바른 ActorHost로 라우팅하는 데 사용.
	KeyRangeStart  string                 `protobuf:"bytes,5,opt,name=key_range_start,json=keyRangeStart,proto3" json:"key_range_start,omitempty"` // split_key 미제공 시 PS의 midpoint 계산용
	KeyRangeEnd    string                 `protobuf:"bytes,6,opt,name=key_range_end,json=keyRangeEnd,proto3" json:"key_range_end,omitempty"`       // split_key 미제공 시 PS의 midpoint 계산용
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteSplitRequest) Reset() {
	*x = ExecuteSplitRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSplitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSplitRequest) ProtoMessage() {}

func (x *ExecuteSplitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSplitRequest.ProtoReflect.Descriptor instead.
func (*ExecuteSplitRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{12}
}

func (x *ExecuteSplitRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *ExecuteSplitRequest) GetSplitKey() string {
	if x != nil {
		return x.SplitKey
	}
	return ""
}

func (x *ExecuteSplitRequest) GetNewPartitionId() string {
	if x != nil {
		return x.NewPartitionId
	}
	return ""
}

func (x *ExecuteSplitRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *ExecuteSplitRequest) GetKeyRangeStart() string {
	if x != nil {
		return x.KeyRangeStart
	}
	return ""
}

func (x *ExecuteSplitRequest) GetKeyRangeEnd() string {
	if x != nil {
		return x.KeyRangeEnd
	}
	return ""
}

type ExecuteSplitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SplitKey      string                 `protobuf:"bytes,1,opt,name=split_key,json=splitKey,proto3" json:"split_key,omitempty"` // PS가 실제 사용한 split key (PM이 routing table 업데이트에 사용)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSplitResponse) Reset() {
	*x = ExecuteSplitResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSplitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSplitResponse) ProtoMessage() {}

func (x *ExecuteSplitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSplitResponse.ProtoReflect.Descriptor instead.
func (*ExecuteSplitResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteSplitResponse) GetSplitKey() string {
	if x != nil {
		return x.SplitKey
	}
	return ""
}

type ExecuteMigrateOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	TargetAddress string                 `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	ActorType     string                 `protobuf:"bytes,4,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"` // PS가 올바른 ActorHost로 라우팅하는 데 사용.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteMigrateOutRequest) Reset() {
	*x = ExecuteMigrateOutRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteMigrateOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMigrateOutRequest) ProtoMessage() {}

func (x *ExecuteMigrateOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMigrateOutRequest.ProtoReflect.Descriptor instead.
func (*ExecuteMigrateOutRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteMigrateOutRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *ExecuteMigrateOutRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *ExecuteMigrateOutRequest) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *ExecuteMigrateOutRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

type ExecuteMigrateOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteMigrateOutResponse) Reset() {
	*x = ExecuteMigrateOutResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteMigrateOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMigrateOutResponse) ProtoMessage() {}

func (x *ExecuteMigrateOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMigrateOutResponse.ProtoReflect.Descriptor instead.
func (*ExecuteMigrateOutResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{15}
}

type PreparePartitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	KeyRangeStart string                 `protobuf:"bytes,2,opt,name=key_range_start,json=keyRangeStart,proto3" json:"key_range_start,omitempty"` // target PS가 올바른 파티션인지 검증용
	KeyRangeEnd   string                 `protobuf:"bytes,3,opt,name=key_range_end,json=keyRangeEnd,proto3" json:"key_range_end,omitempty"`
	ActorType     string                 `protobuf:"bytes,4,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"` // PS가 올바른 ActorHost로 라우팅하는 데 사용.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreparePartitionRequest) Reset() {
	*x = PreparePartitionRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparePartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparePartitionRequest) ProtoMessage() {}

func (x *PreparePartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparePartitionRequest.ProtoReflect.Descriptor instead.
func (*PreparePartitionRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{16}
}

func (x *PreparePartitionRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *PreparePartitionRequest) GetKeyRangeStart() string {
	if x != nil {
		return x.KeyRangeStart
	}
	return ""
}

func (x *PreparePartitionRequest) GetKeyRangeEnd() string {
	if x != nil {
		return x.KeyRangeEnd
	}
	return ""
}

func (x *PreparePartitionRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

type PreparePartitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreparePartitionResponse) Reset() {
	*x = PreparePartitionResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparePartitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparePartitionResponse) ProtoMessage() {}

func (x *PreparePartitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparePartitionResponse.ProtoReflect.Descriptor instead.
func (*PreparePartitionResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{17}
}

type RoutingTableProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Entries       []*RouteEntryProto     `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingTableProto) Reset() {
	*x = RoutingTableProto{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingTableProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingTableProto) ProtoMessage() {}

func (x *RoutingTableProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingTableProto.ProtoReflect.Descriptor instead.
func (*RoutingTableProto) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{18}
}

func (x *RoutingTableProto) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RoutingTableProto) GetEntries() []*RouteEntryProto {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RouteEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	KeyRangeStart string                 `protobuf:"bytes,2,opt,name=key_range_start,json=keyRangeStart,proto3" json:"key_range_start,omitempty"`
	KeyRangeEnd   string                 `protobuf:"bytes,3,opt,name=key_range_end,json=keyRangeEnd,proto3" json:"key_range_end,omitempty"` // "" = 상한 없음
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeAddress   string                 `protobuf:"bytes,5,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	NodeStatus    NodeStatus             `protobuf:"varint,6,opt,name=node_status,json=nodeStatus,proto3,enum=actorbase.v1.NodeStatus" json:"node_status,omitempty"`
	ActorType     string                 `protobuf:"bytes,7,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"` // actor type 식별자
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteEntryProto) Reset() {
	*x = RouteEntryProto{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEntryProto) ProtoMessage() {}

func (x *RouteEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEntryProto.ProtoReflect.Descriptor instead.
func (*RouteEntryProto) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{19}
}

func (x *RouteEntryProto) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *RouteEntryProto) GetKeyRangeStart() string {
	if x != nil {
		return x.KeyRangeStart
	}
	return ""
}

func (x *RouteEntryProto) GetKeyRangeEnd() string {
	if x != nil {
		return x.KeyRangeEnd
	}
	return ""
}

func (x *RouteEntryProto) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RouteEntryProto) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *RouteEntryProto) GetNodeStatus() NodeStatus {
	if x != nil {
		return x.NodeStatus
	}
	return NodeStatus_NODE_STATUS_ACTIVE
}

func (x *RouteEntryProto) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

type ApplyPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyYaml    string                 `protobuf:"bytes,1,opt,name=policy_yaml,json=policyYaml,proto3" json:"policy_yaml,omitempty"` // YAML 형식의 정책 문자열
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPolicyRequest) Reset() {
	*x = ApplyPolicyRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPolicyRequest) ProtoMessage() {}

func (x *ApplyPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPolicyRequest.ProtoReflect.Descriptor instead.
func (*ApplyPolicyRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{20}
}

func (x *ApplyPolicyRequest) GetPolicyYaml() string {
	if x != nil {
		return x.PolicyYaml
	}
	return ""
}

type ApplyPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPolicyResponse) Reset() {
	*x = ApplyPolicyResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPolicyResponse) ProtoMessage() {}

func (x *ApplyPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPolicyResponse.ProtoReflect.Descriptor instead.
func (*ApplyPolicyResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{21}
}

type GetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{22}
}

type GetPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyYaml    string                 `protobuf:"bytes,1,opt,name=policy_yaml,json=policyYaml,proto3" json:"policy_yaml,omitempty"` // 현재 적용 중인 정책 YAML. 없으면 빈 문자열.
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`                          // true이면 AutoPolicy 활성 중
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyResponse) Reset() {
	*x = GetPolicyResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyResponse) ProtoMessage() {}

func (x *GetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{23}
}

func (x *GetPolicyResponse) GetPolicyYaml() string {
	if x != nil {
		return x.PolicyYaml
	}
	return ""
}

func (x *GetPolicyResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type ClearPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearPolicyRequest) Reset() {
	*x = ClearPolicyRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearPolicyRequest) ProtoMessage() {}

func (x *ClearPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearPolicyRequest.ProtoReflect.Descriptor instead.
func (*ClearPolicyRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{24}
}

type ClearPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearPolicyResponse) Reset() {
	*x = ClearPolicyResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearPolicyResponse) ProtoMessage() {}

func (x *ClearPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearPolicyResponse.ProtoReflect.Descriptor instead.
func (*ClearPolicyResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{25}
}

type PartitionStatsProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   string                 `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	ActorType     string                 `protobuf:"bytes,2,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	KeyCount      int64                  `protobuf:"varint,3,opt,name=key_count,json=keyCount,proto3" json:"key_count,omitempty"` // -1이면 actor가 Countable을 구현하지 않음
	Rps           float64                `protobuf:"fixed64,4,opt,name=rps,proto3" json:"rps,omitempty"`                          // 최근 60초 슬라이딩 윈도우 평균
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionStatsProto) Reset() {
	*x = PartitionStatsProto{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionStatsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionStatsProto) ProtoMessage() {}

func (x *PartitionStatsProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionStatsProto.ProtoReflect.Descriptor instead.
func (*PartitionStatsProto) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{26}
}

func (x *PartitionStatsProto) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *PartitionStatsProto) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *PartitionStatsProto) GetKeyCount() int64 {
	if x != nil {
		return x.KeyCount
	}
	return 0
}

func (x *PartitionStatsProto) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{27}
}

type GetStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Partitions     []*PartitionStatsProto `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	NodeRps        float64                `protobuf:"fixed64,2,opt,name=node_rps,json=nodeRps,proto3" json:"node_rps,omitempty"`
	PartitionCount int32                  `protobuf:"varint,3,opt,name=partition_count,json=partitionCount,proto3" json:"partition_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{28}
}

func (x *GetStatsResponse) GetPartitions() []*PartitionStatsProto {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *GetStatsResponse) GetNodeRps() float64 {
	if x != nil {
		return x.NodeRps
	}
	return 0
}

func (x *GetStatsResponse) GetPartitionCount() int32 {
	if x != nil {
		return x.PartitionCount
	}
	return 0
}

type NodeStatsProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeAddr       string                 `protobuf:"bytes,2,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"`
	NodeRps        float64                `protobuf:"fixed64,3,opt,name=node_rps,json=nodeRps,proto3" json:"node_rps,omitempty"`
	PartitionCount int32                  `protobuf:"varint,4,opt,name=partition_count,json=partitionCount,proto3" json:"partition_count,omitempty"`
	Partitions     []*PartitionStatsProto `protobuf:"bytes,5,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeStatsProto) Reset() {
	*x = NodeStatsProto{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatsProto) ProtoMessage() {}

func (x *NodeStatsProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatsProto.ProtoReflect.Descriptor instead.
func (*NodeStatsProto) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{29}
}

func (x *NodeStatsProto) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatsProto) GetNodeAddr() string {
	if x != nil {
		return x.NodeAddr
	}
	return ""
}

func (x *NodeStatsProto) GetNodeRps() float64 {
	if x != nil {
		return x.NodeRps
	}
	return 0
}

func (x *NodeStatsProto) GetPartitionCount() int32 {
	if x != nil {
		return x.PartitionCount
	}
	return 0
}

func (x *NodeStatsProto) GetPartitions() []*PartitionStatsProto {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type GetClusterStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // "" = 모든 노드
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStatsRequest) Reset() {
	*x = GetClusterStatsRequest{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStatsRequest) ProtoMessage() {}

func (x *GetClusterStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStatsRequest.ProtoReflect.Descriptor instead.
func (*GetClusterStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{30}
}

func (x *GetClusterStatsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetClusterStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeStatsProto      `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStatsResponse) Reset() {
	*x = GetClusterStatsResponse{}
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStatsResponse) ProtoMessage() {}

func (x *GetClusterStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_actorbase_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStatsResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_actorbase_proto_rawDescGZIP(), []int{31}
}

func (x *GetClusterStatsResponse) GetNodes() []*NodeStatsProto {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_internal_transport_proto_actorbase_proto protoreflect.FileDescriptor

const file_internal_transport_proto_actorbase_proto_rawDesc = "" +
	"\n" +
	"(internal/transport/proto/actorbase.proto\x12\factorbase.v1\"i\n" +
	"\vSendRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x03 \x01(\tR\tactorType\"(\n" +
	"\fSendResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\xd7\x01\n" +
	"\vScanRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x03 \x01(\tR\tactorType\x127\n" +
	"\x18expected_key_range_start\x18\x04 \x01(\tR\x15expectedKeyRangeStart\x123\n" +
	"\x16expected_key_range_end\x18\x05 \x01(\tR\x13expectedKeyRangeEnd\"(\n" +
	"\fScanResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"2\n" +
	"\x13WatchRoutingRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"m\n" +
	"\fSplitRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12\x1b\n" +
	"\tsplit_key\x18\x02 \x01(\tR\bsplitKey\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x03 \x01(\tR\tactorType\"9\n" +
	"\rSplitResponse\x12(\n" +
	"\x10new_partition_id\x18\x01 \x01(\tR\x0enewPartitionId\"x\n" +
	"\x0eMigrateRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\tR\ftargetNodeId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x03 \x01(\tR\tactorType\"\x11\n" +
	"\x0fMigrateResponse\"\x14\n" +
	"\x12ListMembersRequest\"q\n" +
	"\n" +
	"MemberInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.actorbase.v1.NodeStatusR\x06status\"I\n" +
	"\x13ListMembersResponse\x122\n" +
	"\amembers\x18\x01 \x03(\v2\x18.actorbase.v1.MemberInfoR\amembers\"\xea\x01\n" +
	"\x13ExecuteSplitRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12\x1b\n" +
	"\tsplit_key\x18\x02 \x01(\tR\bsplitKey\x12(\n" +
	"\x10new_partition_id\x18\x03 \x01(\tR\x0enewPartitionId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x04 \x01(\tR\tactorType\x12&\n" +
	"\x0fkey_range_start\x18\x05 \x01(\tR\rkeyRangeStart\x12\"\n" +
	"\rkey_range_end\x18\x06 \x01(\tR\vkeyRangeEnd\"3\n" +
	"\x14ExecuteSplitResponse\x12\x1b\n" +
	"\tsplit_key\x18\x01 \x01(\tR\bsplitKey\"\xa9\x01\n" +
	"\x18ExecuteMigrateOutRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\tR\ftargetNodeId\x12%\n" +
	"\x0etarget_address\x18\x03 \x01(\tR\rtargetAddress\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x04 \x01(\tR\tactorType\"\x1b\n" +
	"\x19ExecuteMigrateOutResponse\"\xa7\x01\n" +
	"\x17PreparePartitionRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12&\n" +
	"\x0fkey_range_start\x18\x02 \x01(\tR\rkeyRangeStart\x12\"\n" +
	"\rkey_range_end\x18\x03 \x01(\tR\vkeyRangeEnd\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x04 \x01(\tR\tactorType\"\x1a\n" +
	"\x18PreparePartitionResponse\"f\n" +
	"\x11RoutingTableProto\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x127\n" +
	"\aentries\x18\x02 \x03(\v2\x1d.actorbase.v1.RouteEntryProtoR\aentries\"\x96\x02\n" +
	"\x0fRouteEntryProto\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12&\n" +
	"\x0fkey_range_start\x18\x02 \x01(\tR\rkeyRangeStart\x12\"\n" +
	"\rkey_range_end\x18\x03 \x01(\tR\vkeyRangeEnd\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12!\n" +
	"\fnode_address\x18\x05 \x01(\tR\vnodeAddress\x129\n" +
	"\vnode_status\x18\x06 \x01(\x0e2\x18.actorbase.v1.NodeStatusR\n" +
	"nodeStatus\x12\x1d\n" +
	"\n" +
	"actor_type\x18\a \x01(\tR\tactorType\"5\n" +
	"\x12ApplyPolicyRequest\x12\x1f\n" +
	"\vpolicy_yaml\x18\x01 \x01(\tR\n" +
	"policyYaml\"\x15\n" +
	"\x13ApplyPolicyResponse\"\x12\n" +
	"\x10GetPolicyRequest\"L\n" +
	"\x11GetPolicyResponse\x12\x1f\n" +
	"\vpolicy_yaml\x18\x01 \x01(\tR\n" +
	"policyYaml\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\"\x14\n" +
	"\x12ClearPolicyRequest\"\x15\n" +
	"\x13ClearPolicyResponse\"\x86\x01\n" +
	"\x13PartitionStatsProto\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x02 \x01(\tR\tactorType\x12\x1b\n" +
	"\tkey_count\x18\x03 \x01(\x03R\bkeyCount\x12\x10\n" +
	"\x03rps\x18\x04 \x01(\x01R\x03rps\"\x11\n" +
	"\x0fGetStatsRequest\"\x99\x01\n" +
	"\x10GetStatsResponse\x12A\n" +
	"\n" +
	"partitions\x18\x01 \x03(\v2!.actorbase.v1.PartitionStatsProtoR\n" +
	"partitions\x12\x19\n" +
	"\bnode_rps\x18\x02 \x01(\x01R\anodeRps\x12'\n" +
	"\x0fpartition_count\x18\x03 \x01(\x05R\x0epartitionCount\"\xcd\x01\n" +
	"\x0eNodeStatsProto\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_addr\x18\x02 \x01(\tR\bnodeAddr\x12\x19\n" +
	"\bnode_rps\x18\x03 \x01(\x01R\anodeRps\x12'\n" +
	"\x0fpartition_count\x18\x04 \x01(\x05R\x0epartitionCount\x12A\n" +
	"\n" +
	"partitions\x18\x05 \x03(\v2!.actorbase.v1.PartitionStatsProtoR\n" +
	"partitions\"1\n" +
	"\x16GetClusterStatsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"M\n" +
	"\x17GetClusterStatsResponse\x122\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1c.actorbase.v1.NodeStatsProtoR\x05nodes*>\n" +
	"\n" +
	"NodeStatus\x12\x16\n" +
	"\x12NODE_STATUS_ACTIVE\x10\x00\x12\x18\n" +
	"\x14NODE_STATUS_DRAINING\x10\x012\x90\x01\n" +
	"\x10PartitionService\x12=\n" +
	"\x04Send\x12\x19.actorbase.v1.SendRequest\x1a\x1a.actorbase.v1.SendResponse\x12=\n" +
	"\x04Scan\x12\x19.actorbase.v1.ScanRequest\x1a\x1a.actorbase.v1.ScanResponse2\xb1\x05\n" +
	"\x17PartitionManagerService\x12T\n" +
	"\fWatchRouting\x12!.actorbase.v1.WatchRoutingRequest\x1a\x1f.actorbase.v1.RoutingTableProto0\x01\x12G\n" +
	"\fRequestSplit\x12\x1a.actorbase.v1.SplitRequest\x1a\x1b.actorbase.v1.SplitResponse\x12M\n" +
	"\x0eRequestMigrate\x12\x1c.actorbase.v1.MigrateRequest\x1a\x1d.actorbase.v1.MigrateResponse\x12R\n" +
	"\vListMembers\x12 .actorbase.v1.ListMembersRequest\x1a!.actorbase.v1.ListMembersResponse\x12^\n" +
	"\x0fGetClusterStats\x12$.actorbase.v1.GetClusterStatsRequest\x1a%.actorbase.v1.GetClusterStatsResponse\x12R\n" +
	"\vApplyPolicy\x12 .actorbase.v1.ApplyPolicyRequest\x1a!.actorbase.v1.ApplyPolicyResponse\x12L\n" +
	"\tGetPolicy\x12\x1e.actorbase.v1.GetPolicyRequest\x1a\x1f.actorbase.v1.GetPolicyResponse\x12R\n" +
	"\vClearPolicy\x12 .actorbase.v1.ClearPolicyRequest\x1a!.actorbase.v1.ClearPolicyResponse2\x84\x03\n" +
	"\x17PartitionControlService\x12I\n" +
	"\bGetStats\x12\x1d.actorbase.v1.GetStatsRequest\x1a\x1e.actorbase.v1.GetStatsResponse\x12U\n" +
	"\fExecuteSplit\x12!.actorbase.v1.ExecuteSplitRequest\x1a\".actorbase.v1.ExecuteSplitResponse\x12d\n" +
	"\x11ExecuteMigrateOut\x12&.actorbase.v1.ExecuteMigrateOutRequest\x1a'.actorbase.v1.ExecuteMigrateOutResponse\x12a\n" +
	"\x10PreparePartition\x12%.actorbase.v1.PreparePartitionRequest\x1a&.actorbase.v1.PreparePartitionResponseBDZBgithub.com/sangchul/actorbase/internal/transport/proto;actorbasepbb\x06proto3"

var (
	file_internal_transport_proto_actorbase_proto_rawDescOnce sync.Once
	file_internal_transport_proto_actorbase_proto_rawDescData []byte
)

func file_internal_transport_proto_actorbase_proto_rawDescGZIP() []byte {
	file_internal_transport_proto_actorbase_proto_rawDescOnce.Do(func() {
		file_internal_transport_proto_actorbase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_proto_actorbase_proto_rawDesc), len(file_internal_transport_proto_actorbase_proto_rawDesc)))
	})
	return file_internal_transport_proto_actorbase_proto_rawDescData
}

var file_internal_transport_proto_actorbase_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_transport_proto_actorbase_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_internal_transport_proto_actorbase_proto_goTypes = []any{
	(NodeStatus)(0),                   // 0: actorbase.v1.NodeStatus
	(*SendRequest)(nil),               // 1: actorbase.v1.SendRequest
	(*SendResponse)(nil),              // 2: actorbase.v1.SendResponse
	(*ScanRequest)(nil),               // 3: actorbase.v1.ScanRequest
	(*ScanResponse)(nil),              // 4: actorbase.v1.ScanResponse
	(*WatchRoutingRequest)(nil),       // 5: actorbase.v1.WatchRoutingRequest
	(*SplitRequest)(nil),              // 6: actorbase.v1.SplitRequest
	(*SplitResponse)(nil),             // 7: actorbase.v1.SplitResponse
	(*MigrateRequest)(nil),            // 8: actorbase.v1.MigrateRequest
	(*MigrateResponse)(nil),           // 9: actorbase.v1.MigrateResponse
	(*ListMembersRequest)(nil),        // 10: actorbase.v1.ListMembersRequest
	(*MemberInfo)(nil),                // 11: actorbase.v1.MemberInfo
	(*ListMembersResponse)(nil),       // 12: actorbase.v1.ListMembersResponse
	(*ExecuteSplitRequest)(nil),       // 13: actorbase.v1.ExecuteSplitRequest
	(*ExecuteSplitResponse)(nil),      // 14: actorbase.v1.ExecuteSplitResponse
	(*ExecuteMigrateOutRequest)(nil),  // 15: actorbase.v1.ExecuteMigrateOutRequest
	(*ExecuteMigrateOutResponse)(nil), // 16: actorbase.v1.ExecuteMigrateOutResponse
	(*PreparePartitionRequest)(nil),   // 17: actorbase.v1.PreparePartitionRequest
	(*PreparePartitionResponse)(nil),  // 18: actorbase.v1.PreparePartitionResponse
	(*RoutingTableProto)(nil),         // 19: actorbase.v1.RoutingTableProto
	(*RouteEntryProto)(nil),           // 20: actorbase.v1.RouteEntryProto
	(*ApplyPolicyRequest)(nil),        // 21: actorbase.v1.ApplyPolicyRequest
	(*ApplyPolicyResponse)(nil),       // 22: actorbase.v1.ApplyPolicyResponse
	(*GetPolicyRequest)(nil),          // 23: actorbase.v1.GetPolicyRequest
	(*GetPolicyResponse)(nil),         // 24: actorbase.v1.GetPolicyResponse
	(*ClearPolicyRequest)(nil),        // 25: actorbase.v1.ClearPolicyRequest
	(*ClearPolicyResponse)(nil),       // 26: actorbase.v1.ClearPolicyResponse
	(*PartitionStatsProto)(nil),       // 27: actorbase.v1.PartitionStatsProto
	(*GetStatsRequest)(nil),           // 28: actorbase.v1.GetStatsRequest
	(*GetStatsResponse)(nil),          // 29: actorbase.v1.GetStatsResponse
	(*NodeStatsProto)(nil),            // 30: actorbase.v1.NodeStatsProto
	(*GetClusterStatsRequest)(nil),    // 31: actorbase.v1.GetClusterStatsRequest
	(*GetClusterStatsResponse)(nil),   // 32: actorbase.v1.GetClusterStatsResponse
}
var file_internal_transport_proto_actorbase_proto_depIdxs = []int32{
	0,  // 0: actorbase.v1.MemberInfo.status:type_name -> actorbase.v1.NodeStatus
	11, // 1: actorbase.v1.ListMembersResponse.members:type_name -> actorbase.v1.MemberInfo
	20, // 2: actorbase.v1.RoutingTableProto.entries:type_name -> actorbase.v1.RouteEntryProto
	0,  // 3: actorbase.v1.RouteEntryProto.node_status:type_name -> actorbase.v1.NodeStatus
	27, // 4: actorbase.v1.GetStatsResponse.partitions:type_name -> actorbase.v1.PartitionStatsProto
	27, // 5: actorbase.v1.NodeStatsProto.partitions:type_name -> actorbase.v1.PartitionStatsProto
	30, // 6: actorbase.v1.GetClusterStatsResponse.nodes:type_name -> actorbase.v1.NodeStatsProto
	1,  // 7: actorbase.v1.PartitionService.Send:input_type -> actorbase.v1.SendRequest
	3,  // 8: actorbase.v1.PartitionService.Scan:input_type -> actorbase.v1.ScanRequest
	5,  // 9: actorbase.v1.PartitionManagerService.WatchRouting:input_type -> actorbase.v1.WatchRoutingRequest
	6,  // 10: actorbase.v1.PartitionManagerService.RequestSplit:input_type -> actorbase.v1.SplitRequest
	8,  // 11: actorbase.v1.PartitionManagerService.RequestMigrate:input_type -> actorbase.v1.MigrateRequest
	10, // 12: actorbase.v1.PartitionManagerService.ListMembers:input_type -> actorbase.v1.ListMembersRequest
	31, // 13: actorbase.v1.PartitionManagerService.GetClusterStats:input_type -> actorbase.v1.GetClusterStatsRequest
	21, // 14: actorbase.v1.PartitionManagerService.ApplyPolicy:input_type -> actorbase.v1.ApplyPolicyRequest
	23, // 15: actorbase.v1.PartitionManagerService.GetPolicy:input_type -> actorbase.v1.GetPolicyRequest
	25, // 16: actorbase.v1.PartitionManagerService.ClearPolicy:input_type -> actorbase.v1.ClearPolicyRequest
	28, // 17: actorbase.v1.PartitionControlService.GetStats:input_type -> actorbase.v1.GetStatsRequest
	13, // 18: actorbase.v1.PartitionControlService.ExecuteSplit:input_type -> actorbase.v1.ExecuteSplitRequest
	15, // 19: actorbase.v1.PartitionControlService.ExecuteMigrateOut:input_type -> actorbase.v1.ExecuteMigrateOutRequest
	17, // 20: actorbase.v1.PartitionControlService.PreparePartition:input_type -> actorbase.v1.PreparePartitionRequest
	2,  // 21: actorbase.v1.PartitionService.Send:output_type -> actorbase.v1.SendResponse
	4,  // 22: actorbase.v1.PartitionService.Scan:output_type -> actorbase.v1.ScanResponse
	19, // 23: actorbase.v1.PartitionManagerService.WatchRouting:output_type -> actorbase.v1.RoutingTableProto
	7,  // 24: actorbase.v1.PartitionManagerService.RequestSplit:output_type -> actorbase.v1.SplitResponse
	9,  // 25: actorbase.v1.PartitionManagerService.RequestMigrate:output_type -> actorbase.v1.MigrateResponse
	12, // 26: actorbase.v1.PartitionManagerService.ListMembers:output_type -> actorbase.v1.ListMembersResponse
	32, // 27: actorbase.v1.PartitionManagerService.GetClusterStats:output_type -> actorbase.v1.GetClusterStatsResponse
	22, // 28: actorbase.v1.PartitionManagerService.ApplyPolicy:output_type -> actorbase.v1.ApplyPolicyResponse
	24, // 29: actorbase.v1.PartitionManagerService.GetPolicy:output_type -> actorbase.v1.GetPolicyResponse
	26, // 30: actorbase.v1.PartitionManagerService.ClearPolicy:output_type -> actorbase.v1.ClearPolicyResponse
	29, // 31: actorbase.v1.PartitionControlService.GetStats:output_type -> actorbase.v1.GetStatsResponse
	14, // 32: actorbase.v1.PartitionControlService.ExecuteSplit:output_type -> actorbase.v1.ExecuteSplitResponse
	16, // 33: actorbase.v1.PartitionControlService.ExecuteMigrateOut:output_type -> actorbase.v1.ExecuteMigrateOutResponse
	18, // 34: actorbase.v1.PartitionControlService.PreparePartition:output_type -> actorbase.v1.PreparePartitionResponse
	21, // [21:35] is the sub-list for method output_type
	7,  // [7:21] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_internal_transport_proto_actorbase_proto_init() }
func file_internal_transport_proto_actorbase_proto_init() {
	if File_internal_transport_proto_actorbase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_proto_actorbase_proto_rawDesc), len(file_internal_transport_proto_actorbase_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_internal_transport_proto_actorbase_proto_goTypes,
		DependencyIndexes: file_internal_transport_proto_actorbase_proto_depIdxs,
		EnumInfos:         file_internal_transport_proto_actorbase_proto_enumTypes,
		MessageInfos:      file_internal_transport_proto_actorbase_proto_msgTypes,
	}.Build()
	File_internal_transport_proto_actorbase_proto = out.File
	file_internal_transport_proto_actorbase_proto_goTypes = nil
	file_internal_transport_proto_actorbase_proto_depIdxs = nil
}
